[toolchain]
channel = "nightly"
targets = ["x86_64-pc-windows-msvc", "x86_64-unknown-linux-gnu"]
components = [
  "cargo",
  "clippy",
  # "llvm-tools",
  # "miri",
  "rust-analyzer",
  "rustc-codegen-cranelift",
  "rustfmt",
]
